### ISSUE TITLE
errror at runtim using transport

### ISSUE THREAD

**Issue by nissshh** [cjmamo/mule-transport-zeromq#4]
I am trying to build a simple flow , rather 2 flows 

1) Flow takes HTTP inbound an send to outbound  ZMQ inproc://reqqueue and has a rquest-reply scope and waits for inbound inproc://resqueue
2) This flow takes inbound on inproc://reqqueue and responds with outbound to inproc://resqueue.

WARN  2013-10-03 13:52:14,945 [main] org.springframework.beans.factory.xml.XmlBeanDefinitionReader: Ignored XML validation warning
org.xml.sax.SAXParseException: schema_reference.4: Failed to read schema document 'http://www.mulesoft.org/schema/mule/devkit/current/mule-devkit.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not xsd:schema.
    at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
    at org.apache.xerces.util.ErrorHandlerWrapper.warning(Unknown Source)
    at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
    at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
....
....
...
...
    at org.mule.module.launcher.DefaultMuleDeployer.deploy(DefaultMuleDeployer.java:47)
    at org.mule.tooling.server.application.ApplicationDeployer.main(ApplicationDeployer.java:127)
ERROR 2013-10-03 13:52:15,017 [main] org.mule.module.launcher.application.DefaultMuleApplication: null
java.lang.ClassNotFoundException: org.mule.api.Capabilities
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at org.mule.module.la

**Comment by cjmamo** [comment]
Which version of Mule are you using? Best is to use Mule 3.4.x for the latest release.

**Comment by nissshh** [comment]
It appears to be outdated issue henc closeing as mule has progressed to 4.X
